version: '3.8'

services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-application
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      # Add any environment variables your application needs
      # - DATABASE_URL=jdbc:postgresql://db:5432/mydatabase
      # - DATABASE_USERNAME=postgres
      # - DATABASE_PASSWORD=postgres
    # If you need to connect to a database, uncomment the following:
    # depends_on:
    #   - db
    networks:
      - app-network

  # Uncomment if you need a database
  # db:
  #   image: postgres:14-alpine
  #   container_name: postgres-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=mydatabase
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# Uncomment if you need a database
# volumes:
#   postgres-data: